#ifndef EMU_CONSTANTS_H
#define EMU_CONSTANTS_H

#include <stdint.h>

#define EMU_MEMORY_SIZE (1024u * 1024u)
#define EMU_LOAD_ADDRESS 0x1000ull
#define EMU_DEFAULT_INSTRUCTION_LIMIT 1000000ull
#define EMU_MAX_BREAKPOINTS 64u
#define EMU_PAGE_SIZE 4096u
#define EMU_STACK_SIZE (64u * 1024u)
#define EMU_STACK_GUARD_PAGES 1u
#define EMU_MAX_MEMORY_MAPPINGS 32u

#define EMU_DEVICE_UART_BASE 0x09000000ull
#define EMU_DEVICE_TIMER_BASE 0x09010000ull
#define EMU_DEVICE_RANDOM_BASE 0x09020000ull
#define EMU_DEVICE_EXCEPTION_BASE 0x09030000ull
#define EMU_DEVICE_KEYBOARD_BASE 0x09040000ull
#define EMU_DEVICE_TERMINAL_BASE 0x09050000ull
#define EMU_DEVICE_FRAME_BASE 0x09060000ull
#define EMU_DEVICE_SIZE 0x00001000ull

#define EMU_UART_DATA_OFFSET 0x00ull
#define EMU_UART_STATUS_OFFSET 0x04ull
#define EMU_TIMER_TICKS_LO_OFFSET 0x00ull
#define EMU_TIMER_TICKS_HI_OFFSET 0x04ull
#define EMU_TIMER_RESET_OFFSET 0x08ull
#define EMU_RANDOM_VALUE_OFFSET 0x00ull
#define EMU_RANDOM_SEED_OFFSET 0x04ull
#define EMU_KBD_STATUS_OFFSET 0x00ull
#define EMU_KBD_DATA_OFFSET 0x04ull
#define EMU_KBD_CONTROL_OFFSET 0x08ull
#define EMU_KBD_STATUS_READY 0x1u
#define EMU_KBD_STATUS_OVERFLOW 0x2u
#define EMU_KBD_CONTROL_CLEAR_OVERFLOW 0x1u
#define EMU_KBD_QUEUE_CAPACITY 16u
#define EMU_TERM_STATUS_OFFSET 0x00ull
#define EMU_TERM_WIDTH_OFFSET 0x04ull
#define EMU_TERM_HEIGHT_OFFSET 0x08ull
#define EMU_TERM_CURSOR_X_OFFSET 0x0cull
#define EMU_TERM_CURSOR_Y_OFFSET 0x10ull
#define EMU_TERM_DATA_OFFSET 0x14ull
#define EMU_TERM_CONTROL_OFFSET 0x18ull
#define EMU_TERM_INDEX_OFFSET 0x20ull
#define EMU_TERM_CELL_OFFSET 0x24ull
#define EMU_TERM_STATUS_DIRTY 0x1u
#define EMU_TERM_CONTROL_CLEAR 0x1u
#define EMU_TERM_CONTROL_HOME 0x2u
#define EMU_TERM_CONTROL_CLEAR_DIRTY 0x4u
#define EMU_TERM_DEFAULT_WIDTH 80u
#define EMU_TERM_DEFAULT_HEIGHT 25u
#define EMU_TERM_MIN_WIDTH 1u
#define EMU_TERM_MIN_HEIGHT 1u
#define EMU_TERM_MAX_WIDTH 160u
#define EMU_TERM_MAX_HEIGHT 100u
#define EMU_TERM_MAX_CELLS (EMU_TERM_MAX_WIDTH * EMU_TERM_MAX_HEIGHT)
#define EMU_FRAME_STATUS_OFFSET 0x00ull
#define EMU_FRAME_COUNTER_LO_OFFSET 0x04ull
#define EMU_FRAME_COUNTER_HI_OFFSET 0x08ull
#define EMU_FRAME_CONTROL_OFFSET 0x0cull
#define EMU_FRAME_STATUS_READY 0x1u
#define EMU_FRAME_CONTROL_CLEAR_READY 0x1u
#define EMU_INTERACTIVE_DEFAULT_FPS 30u
#define EMU_INTERACTIVE_DEFAULT_INSTRUCTIONS_PER_FRAME 1000ull
#define EMU_KEY_ESC 0x1bu
#define EMU_KEY_UP 0x80u
#define EMU_KEY_DOWN 0x81u
#define EMU_KEY_LEFT 0x82u
#define EMU_KEY_RIGHT 0x83u
#define EMU_EXCEPTION_VECTOR_OFFSET 0x00ull
#define EMU_EXCEPTION_CONTROL_OFFSET 0x08ull
#define EMU_EXCEPTION_TIMER_INTERVAL_OFFSET 0x10ull
#define EMU_EXCEPTION_PENDING_OFFSET 0x18ull
#define EMU_EXCEPTION_CAUSE_OFFSET 0x20ull
#define EMU_EXCEPTION_FAULT_ADDRESS_OFFSET 0x28ull
#define EMU_EXCEPTION_INTERRUPTED_PC_OFFSET 0x30ull
#define EMU_EXCEPTION_RESUME_PC_OFFSET 0x38ull
#define EMU_EXCEPTION_DEPTH_OFFSET 0x40ull

#define EMU_EXCEPTION_CONTROL_VECTOR_ENABLE 0x1u
#define EMU_EXCEPTION_CONTROL_INTERRUPTS_ENABLE 0x2u
#define EMU_EXCEPTION_CONTROL_QUEUE_TIMER 0x4u
#define EMU_EXCEPTION_CONTROL_CLEAR_PENDING 0x8u

#define EMU_TOY_KERNEL_MAX_TASKS 8u
#define EMU_TOY_KERNEL_STACK_SIZE (16u * 1024u)
#define EMU_TOY_KERNEL_BOOT_INFO_MAGIC 0x454d554b45524e31ull /* "EMUKERN1" */
#define EMU_TOY_KERNEL_BOOT_INFO_VERSION 2u
#define EMU_TOY_KERNEL_DESCRIPTOR_TABLE_ADDRESS 0x00081000ull
#define EMU_TOY_KERNEL_DESCRIPTOR_MAGIC 0x454d554b5441534bull /* "EMUKTASK" */
#define EMU_TOY_KERNEL_DESCRIPTOR_VERSION 1u
#define EMU_TOY_KERNEL_TASK_NAME_SIZE 16u
#define EMU_TOY_KERNEL_MAILBOX_SLOTS 4u
#define EMU_TOY_KERNEL_MAILBOX_MESSAGE_SIZE 32u
#define EMU_TOY_KERNEL_TRAP_YIELD 0x150u
#define EMU_TOY_KERNEL_TRAP_TASK_EXIT 0x151u
#define EMU_TOY_KERNEL_TRAP_PANIC 0x152u
#define EMU_TOY_KERNEL_TRAP_CONSOLE_WRITE 0x153u
#define EMU_TOY_KERNEL_TRAP_START_TASKS 0x154u
#define EMU_TOY_KERNEL_TRAP_SLEEP 0x155u
#define EMU_TOY_KERNEL_TRAP_SERVICE 0x160u

#define EMU_TOY_SERVICE_TASK_CREATE 1u
#define EMU_TOY_SERVICE_TASK_YIELD 2u
#define EMU_TOY_SERVICE_TASK_EXIT 3u
#define EMU_TOY_SERVICE_TASK_SLEEP 4u
#define EMU_TOY_SERVICE_GET_ID 5u
#define EMU_TOY_SERVICE_GET_INFO 6u
#define EMU_TOY_SERVICE_SEND 7u
#define EMU_TOY_SERVICE_RECV 8u
#define EMU_TOY_SERVICE_CONSOLE_WRITE 9u
#define EMU_TOY_SERVICE_KERNEL_PANIC 10u
#define EMU_TOY_SERVICE_SUPPORTED_MASK \
    ((1ull << EMU_TOY_SERVICE_TASK_CREATE) | (1ull << EMU_TOY_SERVICE_TASK_YIELD) | \
     (1ull << EMU_TOY_SERVICE_TASK_EXIT) | (1ull << EMU_TOY_SERVICE_TASK_SLEEP) | \
     (1ull << EMU_TOY_SERVICE_GET_ID) | (1ull << EMU_TOY_SERVICE_GET_INFO) | \
     (1ull << EMU_TOY_SERVICE_SEND) | (1ull << EMU_TOY_SERVICE_RECV) | \
     (1ull << EMU_TOY_SERVICE_CONSOLE_WRITE) | (1ull << EMU_TOY_SERVICE_KERNEL_PANIC))

#define EMU_TOY_SERVICE_OK 0ll
#define EMU_TOY_SERVICE_ERR_UNKNOWN (-1ll)
#define EMU_TOY_SERVICE_ERR_BAD_ARGUMENT (-2ll)
#define EMU_TOY_SERVICE_ERR_NO_SLOT (-3ll)
#define EMU_TOY_SERVICE_ERR_BAD_ENTRY (-4ll)
#define EMU_TOY_SERVICE_ERR_BAD_STACK (-5ll)
#define EMU_TOY_SERVICE_ERR_BAD_FLAGS (-6ll)
#define EMU_TOY_SERVICE_ERR_NOT_FOUND (-7ll)
#define EMU_TOY_SERVICE_ERR_WOULD_BLOCK (-8ll)

#define EMU_MAP_READ 0x1u
#define EMU_MAP_WRITE 0x2u
#define EMU_MAP_EXEC 0x4u

typedef enum {
    EMU_OK = 0,
    EMU_ERROR = 1,
    EMU_HALTED = 2,
} EmuStatus;

#define EMU_SYSCALL_WRITE 64ull
#define EMU_SYSCALL_EXIT 93ull

#define EMU_SYSCALL_EIO (-5ll)
#define EMU_SYSCALL_EBADF (-9ll)
#define EMU_SYSCALL_ENOSYS (-38ll)

#define EMU_MAX_LOAD_SEGMENTS 16u
#define EMU_MAX_ELF_SEGMENTS EMU_MAX_LOAD_SEGMENTS
#define EMU_MAX_MACHO_SYMBOLS 8u
#define EMU_MAX_MACHO_SYMBOL_NAME 64u

#define EMU_ELF_MAGIC0 0x7fu
#define EMU_ELF_MAGIC1 'E'
#define EMU_ELF_MAGIC2 'L'
#define EMU_ELF_MAGIC3 'F'
#define EMU_ELF_CLASS_64 2u
#define EMU_ELF_DATA_LSB 1u
#define EMU_ELF_VERSION_CURRENT 1u
#define EMU_ELF_ET_EXEC 2u
#define EMU_ELF_ET_DYN 3u
#define EMU_ELF_EM_AARCH64 183u
#define EMU_ELF_PT_LOAD 1u
#define EMU_ELF_PT_INTERP 3u

#define EMU_ELF_PF_X 1u
#define EMU_ELF_PF_W 2u
#define EMU_ELF_PF_R 4u

#define EMU_MACHO_MAGIC_64 0xfeedfacfu
#define EMU_MACHO_MAGIC_32 0xfeedfaceu
#define EMU_MACHO_CIGAM_64 0xcffaedfeu
#define EMU_MACHO_CIGAM_32 0xcefaedfeu
#define EMU_MACHO_FAT_MAGIC 0xbebafecau
#define EMU_MACHO_FAT_MAGIC_64 0xbfbafecau
#define EMU_MACHO_CPU_TYPE_ARM64 0x0100000cu
#define EMU_MACHO_FILETYPE_EXECUTE 2u
#define EMU_MACHO_LC_SEGMENT_64 0x19u
#define EMU_MACHO_LC_LOAD_DYLIB 0x0cu
#define EMU_MACHO_LC_LOAD_DYLINKER 0x0eu
#define EMU_MACHO_LC_DYLD_INFO 0x22u
#define EMU_MACHO_LC_MAIN 0x80000028u
#define EMU_MACHO_LC_DYLD_INFO_ONLY 0x80000022u
#define EMU_MACHO_LC_SYMTAB 0x02u
#define EMU_MACHO_LC_DYSYMTAB 0x0bu
#define EMU_MACHO_LC_CODE_SIGNATURE 0x1du

#endif
